// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type CreateCouponResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoCouponResponse *components.DtoCouponResponse
}

func (c CreateCouponResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCouponResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCouponResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCouponResponse) GetDtoCouponResponse() *components.DtoCouponResponse {
	if c == nil {
		return nil
	}
	return c.DtoCouponResponse
}
