// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type CreateScheduledTaskResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoScheduledTaskResponse *components.DtoScheduledTaskResponse
}

func (c CreateScheduledTaskResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateScheduledTaskResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateScheduledTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateScheduledTaskResponse) GetDtoScheduledTaskResponse() *components.DtoScheduledTaskResponse {
	if c == nil {
		return nil
	}
	return c.DtoScheduledTaskResponse
}
