// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type CreateGroupResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoGroupResponse *components.DtoGroupResponse
}

func (c CreateGroupResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateGroupResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateGroupResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateGroupResponse) GetDtoGroupResponse() *components.DtoGroupResponse {
	if c == nil {
		return nil
	}
	return c.DtoGroupResponse
}
