// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/flexprice/flexprice-go/internal/utils"
	"github.com/flexprice/flexprice-go/models/components"
)

type CreateTenantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created tenant
	DtoTenantResponse *components.DtoTenantResponse
}

func (c CreateTenantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateTenantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateTenantResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateTenantResponse) GetDtoTenantResponse() *components.DtoTenantResponse {
	if c == nil {
		return nil
	}
	return c.DtoTenantResponse
}
