// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type CreateInvoiceResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoInvoiceResponse *components.DtoInvoiceResponse
}

func (c CreateInvoiceResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateInvoiceResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateInvoiceResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateInvoiceResponse) GetDtoInvoiceResponse() *components.DtoInvoiceResponse {
	if c == nil {
		return nil
	}
	return c.DtoInvoiceResponse
}
