// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type CreateCreditGrantResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// Created
	DtoCreditGrantResponse *components.DtoCreditGrantResponse
}

func (c CreateCreditGrantResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(c, "", false)
}

func (c *CreateCreditGrantResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &c, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (c *CreateCreditGrantResponse) GetHTTPMeta() components.HTTPMetadata {
	if c == nil {
		return components.HTTPMetadata{}
	}
	return c.HTTPMeta
}

func (c *CreateCreditGrantResponse) GetDtoCreditGrantResponse() *components.DtoCreditGrantResponse {
	if c == nil {
		return nil
	}
	return c.DtoCreditGrantResponse
}
