// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/models/components"
)

type DeleteScheduledTaskRequest struct {
	// Scheduled Task ID
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (d *DeleteScheduledTaskRequest) GetID() string {
	if d == nil {
		return ""
	}
	return d.ID
}

type DeleteScheduledTaskResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
}

func (d *DeleteScheduledTaskResponse) GetHTTPMeta() components.HTTPMetadata {
	if d == nil {
		return components.HTTPMetadata{}
	}
	return d.HTTPMeta
}
