// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type GetInvoicePreviewResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	DtoInvoiceResponse *components.DtoInvoiceResponse
}

func (g GetInvoicePreviewResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetInvoicePreviewResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetInvoicePreviewResponse) GetHTTPMeta() components.HTTPMetadata {
	if g == nil {
		return components.HTTPMetadata{}
	}
	return g.HTTPMeta
}

func (g *GetInvoicePreviewResponse) GetDtoInvoiceResponse() *components.DtoInvoiceResponse {
	if g == nil {
		return nil
	}
	return g.DtoInvoiceResponse
}
