// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"undefined/internal/utils"
	"undefined/models/components"
)

type QueryWalletResponse struct {
	HTTPMeta components.HTTPMetadata `json:"-"`
	// OK
	TypesListResponseDtoWalletResponse *components.TypesListResponseDtoWalletResponse
}

func (q QueryWalletResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(q, "", false)
}

func (q *QueryWalletResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &q, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (q *QueryWalletResponse) GetHTTPMeta() components.HTTPMetadata {
	if q == nil {
		return components.HTTPMetadata{}
	}
	return q.HTTPMeta
}

func (q *QueryWalletResponse) GetTypesListResponseDtoWalletResponse() *components.TypesListResponseDtoWalletResponse {
	if q == nil {
		return nil
	}
	return q.TypesListResponseDtoWalletResponse
}
